'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Posts', [
        {
          title: '80% of BTC are mined in China, mining equipment is overwhelmingly made in China, and a relatively small number of mostly Chinese mining pools / miners are keeping up the blockchain. Are you worried about this centralization? If not, why not?',
          content: 'Couple folks asked for my source. It’s from the book “Bubble or Revolution” by Mehta, Agasha, and Detroja which I’m reading now (and is pretty good) dated 2019. I know that’s harder to check than a link though.',
          rating: 0,
          userId: 2,
          subredditId: 1,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'People who have been into BTC for 3+ years, what has it been like?',
          content: 'How did you get into it? Did you invest a lot before the initial 20k run?',
          rating: 0,
          userId: 2,
          subredditId: 1,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Bitcoin on exchanges.',
          content: 'Are Exchanges allowed to leverage bitcoin or crypto? So if users hold 1000 BTC on Coinbase. Does coinbase absolutely 100% own 1000 BTC behind the scenes or can they leverage it like a bank, and own less?',
          rating: 0,
          userId: 2,
          subredditId: 1,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'My partner is sure he bought bitcoin in 2010. How to access it?',
          content: 'Hi everyone! This might be a funny post but for the past days my boyfriend says he has been starting to remember buying about a $100 or $200 worth of bitcoin in 2010. He says he has no idea where, on which platform or where it’s stored right now. Does anyone remember where you could buy it back then and how we could access it if that’s still possible? Thank you for any help!',
          rating: 0,
          userId: 2,
          subredditId: 1,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Does anyone think that Zion Williamson should have won rookie of the year of Ja Morant?',
          content: 'Hi everyone! Now I understand that Zion did not play the entire season because of injury but I dont think you can take away what this man did on the court while he was healthy. He was just a total monster! What is everyone elses opinion?',
          rating: 0,
          userId: 3,
          subredditId: 2,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'What do you call a cow with no legs?',
          content: 'Ground beef!',
          rating: 0,
          userId: 3,
          subredditId: 3,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'What did the grape do when he got stepped on?',
          content: 'He let out a little wine',
          rating: 0,
          userId: 4,
          subredditId: 3,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Why did the invisible man turn down the job offer?',
          content: 'Because he couldnt see himself doing it',
          rating: 0,
          userId: 5,
          subredditId: 3,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Which Street fighter game is the best?',
          content: 'In my personal opinion I think SF3 Third Strike is the best. My main issues with SF4 and SF5 is that both have dumb comeback mechanics that rewards losing which I dont understand how any super competitive player could like that. Thoughts?',
          rating: 0,
          userId: 2,
          subredditId: 4,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Why nerf Birdie’s Crouching MP?',
          content: 'Let me preface this by saying that, I agree with the nerfs to his Stand HP and MP. You could really just throw those moves out with little risk. But why would Capcom take away his best anti-air when other characters have extremely similar moves? Jump back jab is an ok replacement but it really feels like Capcom knee jerked nerfed Birdie who is my favorite SF character. You guys feel like it was a needed change or do you agree with me?',
          rating: 0,
          userId: 3,
          subredditId: 4,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'European Brokers to trade US Options',
          content: 'Im looking for a European broker that is zero commission that lets EU citizens trade US options without any fees. I have taken a look at SAXO but they have high fees. Also looked at DeGiro but they didnt have the US options that i want. I am now searching for another. What 0% commission broker do you fellow europeans use for trading US options?',
          rating: 0,
          userId: 2,
          subredditId: 5,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Redfin ($RDFN) Prices Offering of $575 Million of 0% Convertible Senior Notes Due 2025',
          content: 'The notes will have an initial conversion rate of 13.7920 shares of Redfins common stock per $1,000 principal amounts of notes (which is subject to adjustment in certain circumstances). This is equivalent to an initial conversion price of approximately $72.51 per share. The initial conversion price represents a premium of approximately 40% to the $51.79 per share closing price of Redfins common stock on The Nasdaq Global Select Market on October 15, 2020.',
          rating: 0,
          userId: 2,
          subredditId: 5,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Robinhood: 2,000 accounts hacked. Community will survive or...',
          content: 'The app has become notorious for risky investments and frequent trading thats more like gambling than investing. That said, plenty of people are using the app to invest the smart way. They saw opportunity after Marchs stock market crash. Now theyre using the commission-free platform to dodge the fees previous generations of investors accepted. Investing on Robinhood or any other platform doesnt have to be a gamble... or does it? Do you believe in the “Robinhood role” of Robinhood — or is it just another scam for people seeking fast millions?',
          rating: 0,
          userId: 2,
          subredditId: 5,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'What is your favorite Rick and Morty episode?',
          content: 'Title says it all!',
          rating: 0,
          userId: 3,
          subredditId: 6,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'When is the new season of Rick and Morty coming out?',
          content: 'Ive waiting much too long and cant wait no longer!',
          rating: 0,
          userId: 4,
          subredditId: 6,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Why isnt this game more popular than it is?',
          content: 'This is the best free to play experience I have had, way better than Hearthstone by a mile. League of Legends, which is the universe this game is built around is super popular so this just doesent make sense to me',
          rating: 0,
          userId: 5,
          subredditId: 7,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Why isnt this game more popular than it is?',
          content: 'This is the best free to play experience I have had, way better than Hearthstone by a mile. League of Legends, which is the universe this game is built around is super popular so this just doesent make sense to me',
          rating: 0,
          userId: 5,
          subredditId: 7,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Tahm Kench is super OP!',
          content: 'Someone prove me wrong. This card is just ridiculous and combined with the bastion card and the card that heals 4 and increases max health 4 hes unstoppable. Ugh.',
          rating: 0,
          userId: 5,
          subredditId: 7,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'I havent played this game in over 3 years. How hard would it be to try and get back into the game?',
          content: 'I use to play this game non-stop back in the day but trying to get back into this game now seems like it would be very expensive. I believe there are like 4 expansions every year now so 4 times 3 would be 12 expansions.',
          rating: 0,
          userId: 2,
          subredditId: 8,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Which programming language is the best?',
          content: 'Hi all! Im quite new to programming and looking to learn my first language but not sure which to choose. Any help would be very much appreciated. Happy Coding!',
          rating: 0,
          userId: 2,
          subredditId: 9,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Which book would you recommend to prepare for a coding interview?',
          content: 'Ive heard great things about "Cracking the coding interview" but are there any other great books that have prepared you for an interview?',
          rating: 0,
          userId: 2,
          subredditId: 9,
          pictureUrl: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ], {});
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('Posts', null, {});
  }
};
